// Auto-generated by generate-tts script
export const audioManifest = {
  topic: "ReverseEngineering",
  voice: "vi-VN-HoaiMyNeural",
  rate: "+10%",
  totalScenes: 6,
  totalDurationFrames: 1475,
  totalDurationSec: 49.2,
  scenes: [
    {
      id: "scene1_hook",
      text: "Bạn có biết các hacker và chuyên gia bảo mật đọc được bên trong một phần mềm đóng gói mà không có mã nguồn không? Đó chính là Reverse Engineer!",
      audioPath: "audio/ReverseEngineering/scene1_hook.mp3",
      durationInFrames: 256,
    },
    {
      id: "scene2_problem",
      text: "Khi tải một file app hay exe về, bạn chỉ thấy mã máy 0 và 1 hoàn toàn khó hiểu. Vậy làm sao để biết nó đang làm gì thật sự?",
      audioPath: "audio/ReverseEngineering/scene2_problem.mp3",
      durationInFrames: 261,
    },
    {
      id: "scene3_concept1",
      text: "Reverse Engineer là kỹ thuật phân tích ngược: từ chương trình đã biên dịch, suy ngược lại logic, thuật toán và cả mã nguồn ban đầu của nó.",
      audioPath: "audio/ReverseEngineering/scene3_concept1.mp3",
      durationInFrames: 232,
    },
    {
      id: "scene4_concept2",
      text: "Quy trình gồm ba bước: disassembly để đọc assembly, decompile dịch ngược thành pseudocode, rồi debug động để theo dõi chương trình chạy thật.",
      audioPath: "audio/ReverseEngineering/scene4_concept2.mp3",
      durationInFrames: 242,
    },
    {
      id: "scene5_impact",
      text: "Kỹ thuật này được dùng để tìm lỗ hổng bảo mật, phân tích malware, crack phần mềm và cả reverse game mobile để hiểu giao thức kết nối.",
      audioPath: "audio/ReverseEngineering/scene5_impact.mp3",
      durationInFrames: 223,
    },
    {
      id: "scene6_outro",
      text: "Muốn thành chuyên gia bảo mật, hãy bắt đầu với Reverse Engineer ngay hôm nay. Nhớ thả tim và follow kênh để đón xem video tiếp theo nhé!",
      audioPath: "audio/ReverseEngineering/scene6_outro.mp3",
      durationInFrames: 261,
    },
  ],
} as const;
