// Auto-generated by generate-tts script
export const audioManifest = {
  "topic": "SibutraminPhaNaO",
  "voice": "vi-VN-HoaiMyNeural",
  "rate": "+10%",
  "totalScenes": 10,
  "totalDurationFrames": 2687,
  "totalDurationSec": 89.6,
  "scenes": [
    {
      "id": "scene1_hook",
      "text": "Viên thuốc giảm 7 ký trong 7 ngày đang bán tràn lan trên TikTok. Và nó đã phá não một cô gái 21 tuổi.",
      "audioPath": "audio/SibutraminPhaNaO/scene1_hook.mp3",
      "sizeBytes": 43488,
      "estimatedDurationSec": 7.25,
      "durationInFrames": 228
    },
    {
      "id": "scene2_what",
      "text": "Sibutramin là chất ức chế serotonin và norepinephrine, đánh lừa vùng dưới đồi khiến bạn mất hoàn toàn cảm giác đói. FDA từng phê duyệt nó năm 1997.",
      "audioPath": "audio/SibutraminPhaNaO/scene2_what.mp3",
      "sizeBytes": 61920,
      "estimatedDurationSec": 10.32,
      "durationInFrames": 320
    },
    {
      "id": "scene3_scout",
      "text": "Nhưng thử nghiệm SCOUT trên 10.742 bệnh nhân đã vạch trần: Sibutramin tăng 16 phần trăm nguy cơ nhồi máu cơ tim và đột quỵ.",
      "audioPath": "audio/SibutraminPhaNaO/scene3_scout.mp3",
      "sizeBytes": 47520,
      "estimatedDurationSec": 7.92,
      "durationInFrames": 248
    },
    {
      "id": "scene4_ban",
      "text": "Thế giới phản ứng ngay. FDA rút thuốc tháng 10 năm 2010. Việt Nam đình chỉ toàn quốc tháng 4 năm 2011. Sibutramin chính thức là chất cấm.",
      "audioPath": "audio/SibutraminPhaNaO/scene4_ban.mp3",
      "sizeBytes": 69696,
      "estimatedDurationSec": 11.62,
      "durationInFrames": 359
    },
    {
      "id": "scene5_still",
      "text": "Nhưng mở TikTok hôm nay, bạn vẫn thấy: giảm cân siêu tốc, 7 ngày giảm 7 ký. Lời mời chào hấp dẫn, đằng sau là chất cấm 15 năm.",
      "audioPath": "audio/SibutraminPhaNaO/scene5_still.mp3",
      "sizeBytes": 55440,
      "estimatedDurationSec": 9.24,
      "durationInFrames": 288
    },
    {
      "id": "scene6_case",
      "text": "Một cô gái 21 tuổi ở Hà Nội mua thuốc giảm cân trên TikTok. Uống hơn một tháng, rồi cô bất tỉnh. Bệnh viện Bạch Mai chẩn đoán: tổn thương não nặng.",
      "audioPath": "audio/SibutraminPhaNaO/scene6_case.mp3",
      "sizeBytes": 61200,
      "estimatedDurationSec": 10.2,
      "durationInFrames": 316
    },
    {
      "id": "scene7_mechanism",
      "text": "Sibutramin gây co thắt mạch máu não, làm thiếu oxy tế bào thần kinh. Vùng đồi thị bị tổn thương vĩnh viễn, không thể hồi phục.",
      "audioPath": "audio/SibutraminPhaNaO/scene7_mechanism.mp3",
      "sizeBytes": 49536,
      "estimatedDurationSec": 8.26,
      "durationInFrames": 258
    },
    {
      "id": "scene8_signs",
      "text": "Tim đập nhanh, chóng mặt, mất ngủ triền miên, khô miệng. Đó không phải giảm cân, đó là cơ thể đang kêu cứu.",
      "audioPath": "audio/SibutraminPhaNaO/scene8_signs.mp3",
      "sizeBytes": 45792,
      "estimatedDurationSec": 7.63,
      "durationInFrames": 239
    },
    {
      "id": "scene9_protect",
      "text": "Chỉ dùng thuốc có số đăng ký Bộ Y tế. Tuyệt đối không mua thuốc giảm cân rao bán thần tốc trên mạng xã hội.",
      "audioPath": "audio/SibutraminPhaNaO/scene9_protect.mp3",
      "sizeBytes": 40320,
      "estimatedDurationSec": 6.72,
      "durationInFrames": 212
    },
    {
      "id": "scene10_outro",
      "text": "Chia sẻ video này cho người thân trước khi quá muộn. Thông tin chỉ mang tính tham khảo, hãy tham vấn bác sĩ.",
      "audioPath": "audio/SibutraminPhaNaO/scene10_outro.mp3",
      "sizeBytes": 41760,
      "estimatedDurationSec": 6.96,
      "durationInFrames": 219
    }
  ],
  "generatedAt": "2026-09-03T16:04:30.966Z"
} as const;
