// Auto-generated by scripts/gen-motion-showcase.ts (npx tsx scripts/gen-motion-showcase.ts)
export const audioManifest = {
  "topic": "MotionSystemShowcase",
  "voice": "vi-VN-HoaiMyNeural",
  "rate": "+10%",
  "totalScenes": 7,
  "totalDurationFrames": 1146,
  "totalDurationSec": 38.2,
  "scenes": [
    {
      "id": "scene1_hook",
      "text": "Một video dọc đẹp không chỉ nhờ một tấm ảnh đứng yên, mà nhờ một hệ thống chuyển động nhất quán.",
      "audioPath": "audio/MotionSystemShowcase/scene1_hook.mp3",
      "durationInFrames": 173
    },
    {
      "id": "scene2_parallax",
      "text": "Camera hai chấm năm chiều lướt vào đúng chi tiết cần chú ý, thay vì phóng to cả tấm ảnh.",
      "audioPath": "audio/MotionSystemShowcase/scene2_parallax.mp3",
      "durationInFrames": 173
    },
    {
      "id": "scene3_data",
      "text": "Một con số ấn tượng luôn cần đơn vị rõ ràng và nguồn dữ liệu đáng tin.",
      "audioPath": "audio/MotionSystemShowcase/scene3_data.mp3",
      "durationInFrames": 142
    },
    {
      "id": "scene4_montage",
      "text": "Nhiều tư liệu cắt nhanh giúp mạch phim không bao giờ đứng yên quá lâu.",
      "audioPath": "audio/MotionSystemShowcase/scene4_montage.mp3",
      "durationInFrames": 129
    },
    {
      "id": "scene5_diagram",
      "text": "Một cơ chế nhiều bước cần từng trạng thái được vẽ ra rõ ràng, không dồn hết vào một khung hình.",
      "audioPath": "audio/MotionSystemShowcase/scene5_diagram.mp3",
      "durationInFrames": 171
    },
    {
      "id": "scene6_hold",
      "text": "Nhưng đôi khi, hình ảnh cần một khoảng lặng đủ dài để người xem kịp đọc, trước khi chuyển sang ý tiếp theo.",
      "audioPath": "audio/MotionSystemShowcase/scene6_hold.mp3",
      "durationInFrames": 182
    },
    {
      "id": "scene7_outro",
      "text": "Đó là cách một hệ thống thiết kế cảnh nhất quán giúp video kiến thức trở nên chuyên nghiệp và dễ xem hơn.",
      "audioPath": "audio/MotionSystemShowcase/scene7_outro.mp3",
      "durationInFrames": 176
    }
  ],
  "generatedAt": "2026-09-10T03:42:32.113Z"
} as const;

/** Đường dẫn audio tự tạo bằng ffmpeg (sine/noise tổng hợp) — KHÔNG lấy từ
 * video-shotcraft hay nguồn thứ ba nào, tránh mọi rủi ro license nêu ở
 * docs/shotcraft-integration-audit.md mục 3 (quyết định #14). */
export const SYNTHETIC_AUDIO = {
  bgm: "audio/MotionSystemShowcase/sfx/bgm-pad-synthetic.mp3",
  whoosh: "audio/MotionSystemShowcase/sfx/sfx-whoosh-synthetic.mp3",
  tick: "audio/MotionSystemShowcase/sfx/sfx-tick-synthetic.mp3",
  sparkle: "audio/MotionSystemShowcase/sfx/sfx-sparkle-synthetic.mp3",
} as const;
